### ISSUE TITLE
You didn't completed the article

### ISSUE THREAD

**Issue by relbraun** [mweibel/ejabberd-module-guide#2]
The main thing is not clear to me is how do I compile the module and where should I put the module directory in order to compile it? What do I do with the .beam file, where should I put it etc.

Thanks

**Comment by mweibel** [comment]
Hi @relbraun 
yeah sorry I didn't continue with it unfortunately and at the moment I'm not using ejabberd anymore due to switch in jobs. As far as I know the ejabberd docs improved a lot recently, so maybe there's some info there? 
Can't really help you more though. Sorry.
